[package]
name = "ramsey-ticket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "2.0.1"
git2 = "0.13.21"
regex = "1.5.4"
